filebeat.inputs:
- type: filestream
  id: log-generator-5000
  enabled: true
  paths:
    - /var/log/app_logs/*.log

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: "log-generator-5000"
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  ssl:
    certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"

setup.template.name: "log-generator-5000"
setup.template.pattern: "log-generator-5000"

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true
      add_error_key: true
  - drop_fields:
      fields: [ 
        "agent.ephemeral_id", 
        "agent.hostname",
        "agent.id",
        "agent.name",
        "agent.type",
        "agent.version",
        "ecs.version",
        "log.offset",
        "host.name",
        "input.type"
      ]